In [3]:
#1) 다음 리스트를 활용하여 ndarray 자료구조(arr1)을 생성하라

data1 = [1, 2, 3, 4, 5]

In [23]:
import numpy as np
arr1 = nd.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [5]:
#2) 다음 리스트를 활용하여 ndarray 자료구조(arr2)을 생성하라
data2 =  [[1,2,3,4],[5,6,7,8]]

In [25]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
#3)  다음 리스트를 활용하여 ndarray 자료구조(arr3)을 생성하라
data3 = [1,'str']

In [26]:
arr3 = np.array(data3)
arr3

array(['1', 'str'], dtype='<U11')

In [4]:
#4) arr2의 형태를 확인하라(shape)

In [11]:
arr2.shape

(2, 4)

In [5]:
#5)arr2의 자료형을 확인하라(dtype)

In [13]:
arr2.dtype

dtype('int32')

In [6]:
#6) arr2의 항목 수를 확인하라(size)

In [14]:
arr2.size

8

In [7]:
#7) arr2를 전치하라 (T)

In [16]:
arr2.transpose

<function ndarray.transpose>

In [8]:
#8) arr2 + 1,  arr2 - 1, arr2 * 100, arr2 /2 를 각각 구하라

In [19]:
arr2 + 1

arr2 - 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
arr2 * 100

array([[100, 200, 300, 400],
       [500, 600, 700, 800]])

In [21]:
arr2 /2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [9]:
#9) arr3 = np.array([[8,7,6,5],[4,3,2,1]])로 정의하고, 
# arr2 > arr3의 결과를 확인하라

In [28]:
arr3 = np.array([[8, 7, 6, 5], [4, 3, 2, 1]])

arr2 > arr3

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [10]:
#10) array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])를 numpy의
#  aragne() 함수를 활용하여 생성하라

In [31]:
arr4 = np.arange(10)

arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#11) array([0, 2, 4, 6, 8])를 numpy의 
# aragne() 함수를 활용하여 생성하라

In [33]:
arr5 = np.arange(0,9,2)

arr5

array([0, 2, 4, 6, 8])

In [12]:
#12)array([0. , 0.2, 0.4, 0.6, 0.8])를 
# numpy의 aragne() 함수를 활용하여 생성하라

In [37]:
arr6 = np.arange(0,1,0.2)

arr6

array([0. , 0.2, 0.4, 0.6, 0.8])

In [13]:
#13) array([ 0. ,  2.5,  5. ,  7.5, 10. ])를 
# numpy의 aragne() 함수를 활용하여 생성하라

In [39]:
np.arange(0,11,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
#14) np.random.rand의 함수를 활용하여 
# 3행 3열의 난수를 요소로 하는 array를 생성하라

In [40]:
np.random.rand(3,3)

array([[0.66555967, 0.79524939, 0.29069155],
       [0.99175686, 0.23871137, 0.51117587],
       [0.67782024, 0.3966495 , 0.39888882]])

In [15]:
#15) 0부터 10사이의 임의의 정수를 발생시키고
#  이를 원소로 하는 array를 생성하라

In [105]:
a_num = np.random.randint(10, size=(2,5))

a_num

array([[7, 5, 4, 1, 4],
       [8, 9, 1, 5, 0]])

In [108]:
np.array(np.random.randint(0,10))

array(4)

In [16]:
#16) 2행 3열의 구조로 모든 원소를 0으로 하는 array를 생성하라

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#17) 2행 3열의 구조로 모든 원소를 1으로 하는 array를 생성하라

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#18) 3행 3열의 단위 행렬을 생성하라

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#19)[[1, 2, 3, 4],[5, 6, 7, 8]]를 2차원 arrary(arr2)로 생성하라

In [60]:
arr2 = np.array([[1, 2, 3, 4], [5,6,7,8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
#20) arr2의 최댓값을 구하라

In [61]:
arr2.max()

8

In [21]:
#21) arr2의 최솟값을 구하라

In [63]:
arr2.min()

1

In [22]:
#22) arr2의 모든 요소의 평균값을 구하라

In [111]:
arr2.mean()

4.5

In [ ]:
#23) 0부터 5까지 정수를 차례로 발생시키고, 2차원 array(3행 2일)를 생성하라(reshape을 사용하라)


In [69]:
data_n = np.arange(6)
data_n

array([0, 1, 2, 3, 4, 5])

In [70]:
data_n.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
#24) 0부터 23까지 정수를 차례로 발생시키고, 
# 3개의 축을 가지는 3차원 array(4*3*2)를 생성하라(reshape을 사용하라)


In [71]:
data_b = np.arange(24)

data_b.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

* 배열의 인덱싱과 슬라이싱

In [73]:
import numpy as np

a = np.array([1, 2,3,4,5,6, 7,8])


In [74]:
#25) a의 마지막 원소(8)를 인덱싱하라.

In [76]:
a[7]

8

In [26]:
#26) a의 원소 중 1, 3, 5, 7을 슬라이싱하라.

In [80]:
a[0:7:2]

array([1, 3, 5, 7])

In [81]:
b = np.arange(0, 6).reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
#27) b의 가장 윗쪽 행(0번 행)을 조회하라

In [112]:
b[0]

array([0, 1])

In [30]:
#28) b의 원소 중 0을 조회하라

In [113]:
b[0,0]

0

In [31]:
#29) b의 원소 중 [1, 3, 5]를 슬라이싱하라

In [115]:
b[0:3,1]

array([1, 3, 5])

In [116]:
b[:, 1]

array([1, 3, 5])

In [91]:
c = np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
#30) array([ 1,  5,  9, 13])를 슬라이싱하라

In [117]:
c[:, 1]

array([ 1,  5,  9, 13])

In [34]:
#31) array([ 9, 10, 11])를 슬라이싱하라

In [118]:
c[2, 1:]

array([ 9, 10, 11])

In [35]:
#32) array([[0, 1],
    #      [4, 5]])를 슬라이싱 하라

In [119]:
c[:2, :2]

array([[0, 1],
       [4, 5]])

In [103]:
#33) array([[ 5,  6],
#           [ 9, 10]])를 슬라이싱 하라

In [104]:
c[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])